{
 "title": "userhelp",
 "tags": [
  "koopa",
  "prometheus",
  "springboot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group_id", "query": "${VAR_GROUP_ID}" },
   { "name": "artifact_id", "query": "${VAR_ARTIFACT_ID}" },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": "label_values(system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\"},mam_dc)"
   },
   {
    "name": "stage",
    "label": "Stage",
    "query": "label_values(system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\"},mam_stage)"
   },
   {
    "name": "brand",
    "label": "Brand",
    "query": "label_values(system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\"},mam_brand)"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "label_values(system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\"},version)"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Pod Name",
    "query": "label_values(system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\"},kubernetes_pod_name)"
   },
   {
    "name": "interval",
    "label": "Rating interval",
    "query": "3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "description": "The recent CPU usage for the whole system, JVM process and the average CPU usage for JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "system {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "process  {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[1h])",
     "legendFormat": "avg process 1h {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "system {{kubernetes_pod_name}}"
    },
    {},
    {
     "expr": "system_cpu_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "cpu {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads, and peak live thread count since the Java virtual machine started or peak was reset.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "live {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "daemon {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_peak_threads{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "peak {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "description": "The open and maximum file descriptor count.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "open {{kubernetes_pod_name}}"
    },
    {
     "expr": "process_files_max_files{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "max {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests / Min",
   "type": "graph",
   "description": "Incoming HTTP requests count.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60) OR on() vector(0)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Median Request Duration (ms)",
   "type": "graph",
   "description": "Incoming HTTP request duration.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(histogram_quantile(0.5, sum by (kubernetes_pod_name, le) (rate(http_server_requests_seconds_bucket{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]))) * 1000)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "round(histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]))) * 1000) OR on() vector(0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Server Errors / Min",
   "type": "graph",
   "description": "Server error count (5xx).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",status=~\"5..\"}[$interval]) * 60",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",status=~\"5..\"}[$interval])) * 60 OR on() vector(0)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Client Errors / Min",
   "type": "graph",
   "description": "Client errors count (4xx).",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",status=~\"4..\"}[$interval]) * 60",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",status=~\"4..\"}[$interval])) * 60 OR on() vector(0)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Slow Requests (>1s) / Min",
   "type": "graph",
   "description": "Count of the slow requests with duration over 1s.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum by (kubernetes_pod_name) (rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60) - sum by (kubernetes_pod_name) (rate(http_server_requests_seconds_bucket{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",le=\"1.0\"}[$interval]) * 60))",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(round(sum by (kubernetes_pod_name) (rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60) - sum by (kubernetes_pod_name) (rate(http_server_requests_seconds_bucket{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",le=\"1.0\"}[$interval]) * 60))) OR on() vector(0)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Requests per App / Min",
   "type": "graph",
   "description": "Incoming HTTP requests count per client application.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (clientName) (rate(http_server_requests_app_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60) OR on() vector(0)",
     "legendFormat": "{{clientName}}"
    }
   ]
  },
  {
   "title": "Requests per Resource / Min",
   "type": "graph",
   "description": "Incoming HTTP requests count per REST resource.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60) OR on() vector(0)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Log Events / Min",
   "type": "graph",
   "description": "Log events count.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logback_events_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60",
     "legendFormat": "{{kubernetes_pod_name}} {{level}}"
    },
    {
     "expr": "sum by (level) (rate(logback_events_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60)",
     "legendFormat": "sum {{level}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Total",
     "type": "graph",
     "description": "The total amount of used, committed and maximum memory.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(kubernetes_pod_name) (jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by(kubernetes_pod_name) (jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "committed  {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by(kubernetes_pod_name) (jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
       "legendFormat": "max  {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "description": "The amount of used, committed and maximum heap memory.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"heap\"})",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"heap\"})",
       "legendFormat": "committed {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"heap\"})",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "description": "The amount of used, committed and maximum non-heap memory.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"nonheap\"})",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"nonheap\"})",
       "legendFormat": "committed {{kubernetes_pod_name}}"
      },
      {
       "expr": "sum by (kubernetes_pod_name) (jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",area=\"nonheap\"})",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pool (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "graph",
     "description": "The amount of used, committed and maximum eden space heap memory.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Eden Space\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Eden Space\"}",
       "legendFormat": "commited {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Eden Space\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Old Generation",
     "type": "graph",
     "description": "The amount of used, committed and maximum old generation heap memory.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Old Gen\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Old Gen\"}",
       "legendFormat": "commited {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Old Gen\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "graph",
     "description": "The amount of used, committed and maximum survivor space heap memory.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Survivor Space\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Survivor Space\"}",
       "legendFormat": "commited {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=~\".*Survivor Space\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metaspace",
     "type": "graph",
     "description": "The amount of used, committed and maximum metaspace memory.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Metaspace\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Metaspace\"}",
       "legendFormat": "commited {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Metaspace\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "graph",
     "description": "The amount of used, committed and maximum compressed class space memory.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Compressed Class Space\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Compressed Class Space\"}",
       "legendFormat": "commited {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Compressed Class Space\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Code Cache",
     "type": "graph",
     "description": "The amount of used, committed and maximum code cache memory.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Code Cache\"}",
       "legendFormat": "used  {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_committed_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Code Cache\"}",
       "legendFormat": "commited  {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_memory_max_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\",id=\"Code Cache\"}",
       "legendFormat": "max  {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers Size",
     "type": "graph",
     "description": "An estimate of the memory that the JVM is using and of the total capacity of direct buffer pool.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"direct\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"direct\"}",
       "legendFormat": "capacity {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Direct Buffers Count",
     "type": "graph",
     "description": "An estimate of the number of direct buffers in the pool.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"direct\"}",
       "legendFormat": "count {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers Size",
     "type": "graph",
     "description": "An estimate of the memory that the JVM is using and of the total capacity of mapped buffer pool.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"mapped\"}",
       "legendFormat": "used {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"mapped\"}",
       "legendFormat": "capacity {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Mapped Buffers Count",
     "type": "graph",
     "description": "An estimate of the number of mapped buffers in the pool.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\", id=\"mapped\"}",
       "legendFormat": "count {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections / Min",
     "type": "graph",
     "description": "Number of GC occurrence per minute.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval]) * 60",
       "legendFormat": "{{action}} {{cause}} {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Allocation/Promotion",
     "type": "graph",
     "description": "The size of the young generation memory pool and the count of positive increases in the size of the old generation memory pool before and after garbage collections.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "allocated {{kubernetes_pod_name}}"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "promoted {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Live/Max Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC and max size of old generation memory pool.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "max {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_gc_live_data_size_bytes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "live {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "description": "Average and max pause duration.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_seconds_sum{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])/increase(jvm_gc_pause_seconds_count{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "avg {{action}} ({{cause}}) {{kubernetes_pod_name}}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "max {{action}} ({{cause}})  {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the JVM.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
       "legendFormat": "loaded {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Class Load/Unload Rate",
     "type": "graph",
     "description": "JVM class load and unload rate.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "class load rate {{kubernetes_pod_name}}"
      },
      {
       "expr": "delta(jvm_classes_unloaded_classes_total{groupId=\"$group_id\",artifactId=\"$artifact_id\",mam_dc=~\"$datacenter\",mam_stage=~\"$stage\",mam_brand=~\"$brand\",app_kubernetes_io_version=~\"$version\",kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "class unload rate {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}